version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13

    working_directory: ~/repo

    steps:
      - checkout

      - run: mix local.hex --force 
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix format
      - run: mix credo --strict
      - run: mix test
